name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  my_job:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: hyperskill/azure-login@v3.0.0
        with:
            # Azure client id
            client_id: 7ab6d6ea-b98a-4a42-9b95-2e12dc2a80fa
            # Azure client secret
            client_secret: YCY8Q~l3dNLzf6zi1-U-fytT08LuA38WKfHKdaxC
            # Azure subscription id
            subscription_id: 210ae65d-cb56-414b-a96e-c11a9a472e8d
            # Azure tenant id
            tenant_id: 94068d3d-e158-4e7b-9393-feeaf9ac5cc6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Verify Terraform
        run: terraform version
      
      - name: Debug Files
        run: |
          pwd
          ls -la
          find . -name "*.tf"
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        run: terraform apply -auto-approve

    
